export const CATEGORIES_ACTION_TYPES = {
    FETCH_CARTEGORIES_START: 'category/FETCH_CATEGORIES_START',
    FETCH_CARTEGORIES_SUCCESS: 'category/FETCH_CATEGORIES_SUCCESS',
    FETCH_CARTEGORIES_FAILED: 'category/FETCH_CATEGORIES_FAILED',
};